import type { DefaultSession } from "next-auth";

import type { UserRole } from "@/lib/roles";

// `@/*` -> `./src/*` (`tsconfig.json`) resolves from this file too, even
// though it lives in `types/` rather than under `src/`: TypeScript's `paths`
// map is resolved against the project's `baseUrl`/config, not against the
// importing file's own location, and `scripts/seed-guides.ts` (also outside
// `src/`) already relies on the same thing for `@/lib/mongodb`.

// Module augmentation for Auth.js v5 (next-auth@beta). This file is picked up
// automatically because `tsconfig.json` includes `**/*.ts`; unlike
// `types/routes.d.ts` and `types/validator.ts` in this same folder, it is
// NOT generated by Next.js and is safe to hand-edit.
declare module "next-auth" {
  /** The object returned by the Credentials provider's `authorize()`. */
  interface User {
    username: string;
    role: UserRole;
  }

  interface Session {
    user: {
      id: string;
      username: string;
      role: UserRole;
    } & DefaultSession["user"];
  }
}

// NOTE: `next-auth/jwt`'s `JWT` is a type-only re-export of `@auth/core/jwt`'s
// `JWT` (`export * from "@auth/core/jwt"`), and the `jwt`/`session`
// callbacks in `src/lib/auth.ts` are typed against the `@auth/core/jwt`
// declaration directly. Augmenting `"next-auth/jwt"` does NOT merge into
// that declaration (see nextauthjs/next-auth#9571, #12094) - augment
// `"@auth/core/jwt"` instead.
declare module "@auth/core/jwt" {
  interface JWT {
    id: string;
    username: string;
    /**
     * Epoch ms after which the token stops being trusted on its own and
     * the `jwt` callback must exchange `refreshToken` for a successor.
     */
    accessTokenExpires: number;
    /**
     * The session's current refresh token, in plaintext. Safe to keep here
     * and nowhere else client-side: Auth.js encrypts this JWT (JWE) before
     * it ever becomes a cookie, and that cookie is HttpOnly - so the token
     * is opaque both to the browser's JavaScript and to anyone reading the
     * cookie jar. The server stores only its SHA-256 hash.
     */
    refreshToken: string;
    /** Epoch ms at which `refreshToken` itself expires. */
    refreshTokenExpires: number;
    /**
     * A snapshot of the user's role as of the last time this token was
     * minted or rotated - at most `ACCESS_TOKEN_TTL_MS` (15 minutes) stale,
     * since the `jwt` callback's rotation branch re-reads it from the
     * database on every rotation (`src/lib/auth.ts`, `services/users.ts`).
     * It is not a live read: a role change made *within* someone's current
     * 15-minute access window won't be reflected here until the next
     * rotation. Treat it as good enough to render (nav links, an eventual
     * "you're a guide" badge) but never as authorization for a privileged
     * mutation - re-check `getUserRole` against the database at the point
     * of the mutation instead of trusting this claim.
     */
    role: UserRole;
  }
}

export {};
