import type { DefaultSession } from "next-auth";

// Module augmentation for Auth.js v5 (next-auth@beta). This file is picked up
// automatically because `tsconfig.json` includes `**/*.ts`; unlike
// `types/routes.d.ts` and `types/validator.ts` in this same folder, it is
// NOT generated by Next.js and is safe to hand-edit.
declare module "next-auth" {
  /** The object returned by the Credentials provider's `authorize()`. */
  interface User {
    username: string;
  }

  interface Session {
    user: {
      id: string;
      username: string;
    } & DefaultSession["user"];
  }
}

// NOTE: `next-auth/jwt`'s `JWT` is a type-only re-export of `@auth/core/jwt`'s
// `JWT` (`export * from "@auth/core/jwt"`), and the `jwt`/`session`
// callbacks in `src/lib/auth.ts` are typed against the `@auth/core/jwt`
// declaration directly. Augmenting `"next-auth/jwt"` does NOT merge into
// that declaration (see nextauthjs/next-auth#9571, #12094) - augment
// `"@auth/core/jwt"` instead.
declare module "@auth/core/jwt" {
  interface JWT {
    id: string;
    username: string;
    /**
     * Epoch ms after which the token stops being trusted on its own and
     * the `jwt` callback must exchange `refreshToken` for a successor.
     */
    accessTokenExpires: number;
    /**
     * The session's current refresh token, in plaintext. Safe to keep here
     * and nowhere else client-side: Auth.js encrypts this JWT (JWE) before
     * it ever becomes a cookie, and that cookie is HttpOnly - so the token
     * is opaque both to the browser's JavaScript and to anyone reading the
     * cookie jar. The server stores only its SHA-256 hash.
     */
    refreshToken: string;
    /** Epoch ms at which `refreshToken` itself expires. */
    refreshTokenExpires: number;
  }
}

export {};
